name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black ruff
      - name: Run pre-commit on all files
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Fail if .env-like files are tracked
        run: |
          matches=$(git ls-files | grep -E '(^|/)(\\.env(\\..*)?$|.*\\.env$)' || true)
          if [ -n "$matches" ]; then
            echo "Found forbidden env files tracked in repo:";
            echo "$matches";
            exit 1;
          fi